import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import AosInitializer from '@/components/AosInitializer'; // path harus sesuai struktur folder Anda

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Memo Web - RPL 2',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${montserrat.variable} antialiased`}>
        <AosInitializer />
        {children}
      </body>
    </html>
  );
}
